name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./ReShade.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check Repo and Sub Modules
      uses: actions/checkout@v3
      with:
        submodules: recursive
  
    - name: Add Python to PATH
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build 64-Bit
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="64-bit" ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build 32-Bit
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="32-bit" ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build Setup
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration="Release Setup" ${{env.SOLUTION_FILE_PATH}}
    
    - name: Upload 64-Bit DLL
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
       name: ReShade64-NetUnlocked # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
       path: ./bin/x64/Release/ReShade64.dll
       
    - name: Upload 32-Bit DLL
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
       name: ReShade32-NetUnlocked # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
       path: ./bin/Win32/Release/ReShade32.dll
       
    - name: Upload Setup EXE
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
       name: ReShadeSetup-NetUnlocked # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
       path: ./bin/AnyCPU/Release/
       
    - name: Upload Shader PKG
      uses: actions/upload-artifact@v3.1.1
      with: 
        name: ReShadeShader-PKG
        path: ./shaders/*
   
